package net.ravendb.abstractions.data;

import net.ravendb.abstractions.json.linq.RavenJObject;

/**
 * The result of a single operation inside a batch
 */
public class BatchResult {
  private Etag etag;
  private String method;
  private String key;
  private RavenJObject metadata;
  private RavenJObject additionalData;
  private PatchResult patchResult;
  private Boolean deleted;

  /**
   * Additional operation data.
   */
  public RavenJObject getAdditionalData() {
    return additionalData;
  }

  /**
   * Indicates if the document was deleted (null if not DELETE operation)
   * Value:
   * - true - if the document was deleted
   * - false - if it did not exist.
   */
  public Boolean getDeleted() {
    return deleted;
  }

  /**
   * Etag generated by the operation (null if not applicable).
   */
  public Etag getEtag() {
    return etag;
  }

  /**
   * Key of a document.
   */
  public String getKey() {
    return key;
  }

  /**
   * Updated metadata of a document.
   */
  public RavenJObject getMetadata() {
    return metadata;
  }

  /**
   * Method used by the operation (PUT,DELETE,PATCH).
   */
  public String getMethod() {
    return method;
  }

  /**
   * Result of a PATCH operation.
   */
  public PatchResult getPatchResult() {
    return patchResult;
  }

  /**
   * Additional operation data.
   * @param additionalData
   */
  public void setAdditionalData(RavenJObject additionalData) {
    this.additionalData = additionalData;
  }

  /**
   * Indicates if the document was deleted (null if not DELETE operation)
   * Value:
   * - true - if the document was deleted
   * - false - if it did not exist.
   * @param true if the document was deleted, false if it did not exist.
   */
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  /**
   * Etag generated by the operation (null if not applicable).
   * @param etag
   */
  public void setEtag(Etag etag) {
    this.etag = etag;
  }

  /**
   * Key of a document.
   * @param key
   */
  public void setKey(String key) {
    this.key = key;
  }

  /**
   * Updated metadata of a document.
   * @param metadata
   */
  public void setMetadata(RavenJObject metadata) {
    this.metadata = metadata;
  }

  /**
   * Method used by the operation (PUT,DELETE,PATCH).
   * @param method
   */
  public void setMethod(String method) {
    this.method = method;
  }

  /**
   * Result of a PATCH operation.
   * @param patchResult
   */
  public void setPatchResult(PatchResult patchResult) {
    this.patchResult = patchResult;
  }

}
