package net.ravendb.client.serverwide.operations.builder;

public interface IOrchestratorTopologyConfigurationBuilder extends ITopologyConfigurationBuilderBase<IOrchestratorTopologyConfigurationBuilder> {
}
